---
name: Continuous Integration

on:  # yamllint disable-line rule:truthy
 merge_group:
 pull_request:

jobs:
 tests:
  runs-on: ubuntu-latest
  steps:
  - name: Run tests
    run: |
     sleep 2; echo "Tests Successful"
 lints:
  runs-on: ubuntu-latest
  steps:
  - name: Run tests
    run: |
     sleep 2; echo "Lints Successful"
 expensive_checks:
  if: github.event_name == 'merge_group'
  runs-on: ubuntu-latest
  steps:
  - name: Run tests
    run: |
     sleep 300; echo "Expensive checks Successful"

 can_enqueue:
  needs: [tests, lints]
  if: always() && github.event_name != 'merge_group'
  permissions:
   actions: read
  runs-on: ubuntu-latest
  steps:
   - env:
      NEEDS: "${{toJSON(needs)}}"
     name: Transform outcomes
     run: |
      ok=$(echo "$NEEDS" | jq -r '[.[] | .result | IN("success","skipped")] | all')
      test "$ok" = "true"

 can_merge:
  needs: [tests, lints, expensive_checks]
  if: always() && github.event_name == 'merge_group'
  # Same thing as above, from here on:
  permissions:
   actions: read
  runs-on: ubuntu-latest
  steps:
   - env:
      NEEDS: "${{toJSON(needs)}}"
     name: Transform outcomes
     run: |
      ok=$(echo "$NEEDS" | jq -r '[.[] | .result | IN("success","skipped")] | all')
      test "$ok" = "true"
  
 can_see_status:
  runs-on: ubuntu-latest
  steps:
   - run: true
